<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Микола Кузін, старший аналітик, BRDO">
<meta name="dcterms.date" content="2025-12-23">

<title>Вплив зміни порогу реєстрації ПДВ на підприємців у сфері громадського харчування</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d4be639c637f3db3c684c66cefad7e0c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Вплив зміни порогу реєстрації ПДВ на підприємців у сфері громадського харчування</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Микола Кузін, старший аналітик, BRDO </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><span class="smallcaps"><strong>Резюме</strong>. Міністерство фінансів пропонує встановити поріг обов’язкової реєстрації ПДВ при перевищенні 1 млн грн доходу на рік для підприємців на спрощеній системи оподаткування (ССО). Ми змоделювали вплив цієї ініціативи на сферу громадського харчування, де зараз працює близько 88 тисяч підприємців, з них — понад 47 тисяч ФОПів на ССО. Розрахунки показують, що “жорсткий сценарій” (ліміт 1 млн грн) підвищить ефективну ставку податку в рази та через низьку маржинальність бізнесу лишить поза точкою безокупності чверть від усіх підприємців сфери. Альтернативний “євроінтеграційний сценарій” (ліміт ~4.16 млн грн) є м’якшим, але без перехідного періоду також виб’є з ринку значну кількість підприємців. В тексті наведені аргументи, чому вирівнювання лімітів має бути поетапним та йти разом зі спрощенням адміністрування системи ПДВ, інакше отримаємо не розширення податкової бази, як очікує Мінфін, а зворотний ефект — перехід у тінь або еміграцію активних громадян.</span></p>
<blockquote class="blockquote">
<p><strong>Зміни від 06 січня 2025</strong>. Центр економічної стратегії передав дані з актуальним розподілом доходів підприємців сфери (на зміну нашому припущенню щодо розподілу доходів), внаслідок цього оцінка кількості мікробізнесу, на кого негативно вплинуть зміни при встановленні ліміту у 1 млн грн, знизилася з третини до чверті від усіх підприємців сфери. Поточна редакція тексту викладена вже з врахуванням цих даних. Ключові висновки лишилися незмінними.</p>
</blockquote>
<p>В межах досягнутої з МВФ&nbsp;<a href="https://www.imf.org/en/news/articles/2025/11/26/pr-25399-ukraine-agreement-on-new-us-8-point-1-bil-48mo-eff-arrangement">угоди</a>&nbsp;щодо виділення розширеного фінансування, уряд України взяв зобов’язання розширити базу оподаткування, зокрема, прибравши пільгове звільнення від реєстрації ПДВ. У підготованому Міністерством фінансів&nbsp;<a href="https://mof.gov.ua/uk/draft_regulatory_acts_for_discussion_in_2025-819">проєкті</a>&nbsp;Закону України запропоновано досягти цих цілей через вирівнювання порогу реєстрації на рівні 1 млн грн як для платників на загальній, так і на спрощеній системі оподаткування (ССО).</p>
<p>Наразі порогом реєстрації ПДВ для підприємців на ССО виступають відповідні річні ліміти доходу для кожної з груп: у 2025 році це близько 1.4 млн грн для першої групи, 7.2 млн для другої і 10.1 млн — для третьої групи. На прикладі сфери громадського харчування (КВЕД 56, “Діяльність із забезпечення стравами та напоями”) оцінимо потенційний економічний ефект від реалізації різних сценаріїв зміни порогу реєстрації ПДВ.&nbsp;</p>
<section id="сфера-громадського-харчування-ключова-статистика-та-припущення" class="level3">
<h3 class="anchored" data-anchor-id="сфера-громадського-харчування-ключова-статистика-та-припущення"><strong>Сфера громадського харчування: ключова статистика та припущення</strong></h3>
<p>Станом на 31 грудня 2024 в Україні 88,325 підприємців надавали послуги із забезпечення стравами та напоями. За даними ДПС, 81.33% або 71,827 цих підприємців діяли як ФОП; з цих ФОП 34.27% перебували на загальній системі оподаткування, решта — на ССО.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Таким чином, на кінець 2024 року маємо 47,210 ФОП, що надавали послуги громадського харчування і перебували на спрощеній системі оподаткування.</p>
<p>Погляньмо на розподіл доходів ФОП на ССО від діяльності у сфері громадського харчування<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Група ФОП</strong></td>
<td><strong>Кількість ФОП</strong></td>
<td><strong>Медіанний дохід, млн грн</strong></td>
<td><strong>Кількість ФОП з &lt;1 млн грн доходу</strong></td>
<td><strong>Частка ФОП з &lt;1 млн грн доходу</strong></td>
</tr>
<tr class="even">
<td>2 Група, ССО</td>
<td>39,148</td>
<td>2.92</td>
<td>11,488</td>
<td>29.3%</td>
</tr>
<tr class="odd">
<td>3 Група, ССО</td>
<td>8,062</td>
<td>2.64</td>
<td>4,500</td>
<td>55.8%</td>
</tr>
</tbody>
</table>
<p>Згідно з цією моделлю, медіанний дохід ФОП на 2й групі складає 2.92 млн грн, на 3й — 2.64 млн грн.</p>
<p>Особливістю сфери громадського харчування є низька частка витрат, підтверджених податковими накладними. Це зумовлено купівлею частини продуктів на ринку, або у фермерів-ФОПів, які не є платниками ПДВ; якщо орендодавець є ФОПом, бізнес також не отримає податкового кредиту. Припускаємо, що податковий кредит заклад громадського харчування отримає на 30% свого обороту. Відповідно, ефективна ставка ПДВ складатиме 11.67% від обороту. Виходимо з того, що при перевищенні ліміту бізнес сплачуватиме ПДВ з усього обсягу оподатковуваних операцій. Крім того, адміністрування ПДВ в Україні вимагає професійної підготовки, додамо сюди додаткові адміністративні витрати із частковою залученістю бухгалтера у розрахунку 6,000 грн/місяць, або 72,000 грн/рік .</p>
<p>Важливою характеристикою сфери громадського харчування є еластичність попиту за ціною, коли бізнес не може просто підвищити ціни і не втратити клієнтів. Відповідно, щоби утримати клієнтів, бізнес компенсуватиме частину додаткових витрат за рахунок власного прибутку.</p>
</section>
<section id="а.-жорсткий-сценарій-реєстрація-пдв-при-перевищенні-річного-доходу-у-1-млн-грн" class="level3">
<h3 class="anchored" data-anchor-id="а.-жорсткий-сценарій-реєстрація-пдв-при-перевищенні-річного-доходу-у-1-млн-грн"><strong>а. Жорсткий сценарій — реєстрація ПДВ при перевищенні річного доходу у 1 млн грн</strong></h3>
<p>За жорсткого сценарію ті, хто зараз перебуває на спрощеній системі, при перевищенні ліміту доходів за рік у 1 млн грн мають реєструватися платниками ПДВ і сплачувати ПДВ з усього обсягу оподатковуваних операцій.</p>
<p>Моделювання показує, що при досягненні значення доходу у 1 млн грн, ефективна ставка податку для ФОП 2ї групи зростає з 3.41%, у найнижчій точці на межі до 1 млн грн, до 13.87% - 22.08%: чим більший дохід в межах ліміту спрощеної системи, тим меншою буде ефективна ставка. У випадку 3ї групи ефективна ставка податку піднімається з близько 7% до 18.98% - 25.2% з обороту.&nbsp;</p>
<p>При розрахунку ефективної ставки податків враховуємо ЄП, ЄСВ, військовий збір для відповідної групи спрощеної системи, ефективну ставку ПДВ у розмірі 11.67%, а також додаткові адміністративні витрати на бухгалтера у розмірі 72,000 грн/рік.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 574 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Згідно з наведеним розподілом доходів, за цього сценарію у сфері громадського харчування вказані зміни у системі оподаткування вплинуть на діяльність 66.1% підприємців-ФОП на ССО, або понад третину від усіх, хто надає послуги у цій сфері.</p>
<p>У <a href="https://rau.ua/novyni/viruchka-serednij-chek-2023-poster/">дослідженні</a> Poster за 2023 рік йдеться, що у 63% випадків рентабельність ресторанного бізнесу не перевищує 15%. Зважаючи на еластичність попиту по ціні і вказаний рівень рентабельності бізнесу, підняття ефективної ставки податку призведе до тінізації або закриття близько чверті усіх підприємців, що зараз працюють у сфері — з найбільшим шоком для мікробізнесу.</p>
</section>
<section id="b.-євроінтеграційний-сценарій-сплата-пдв-при-перевищенні-річного-доходу-у-4.16-млн-грн" class="level3">
<h3 class="anchored" data-anchor-id="b.-євроінтеграційний-сценарій-сплата-пдв-при-перевищенні-річного-доходу-у-4.16-млн-грн">b. Євроінтеграційний сценарій — сплата ПДВ при перевищенні річного доходу у 4.16 млн грн</h3>
<p>При підвищенні порогового значення переходу на ПДВ до 85,000 тис євро (~4.16 млн грн), що відповідає пороговому значенню для реєстрації ПДВ у країнах-членах ЄС, частка підприємців, що підпадуть під вимоги реєстрації та сплати ПДВ становитиме 54.01% для 2ї групи та 74.82% для 3ї групи.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 571 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3525736</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3525736</code></pre>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Група ФОП</strong></td>
<td><strong>% ФОП на ССО, на кого вплинуть зміни</strong></td>
<td><strong>Середня ефективна ставка податку для них%</strong></td>
</tr>
<tr class="even">
<td>2 Група</td>
<td>37.21%</td>
<td>13.74%</td>
</tr>
<tr class="odd">
<td>3 Група</td>
<td>25.79%</td>
<td>18.87%</td>
</tr>
</tbody>
</table>
<p>Враховуючи значення рентабельності у сфері, з третини підприємців сфери, яких загалом торкнуться такі зміни, при піднятті середньої ефективної ставки податку до 13.7-18.9%, нижче рівня окупності опиняться близько 10.5 тисяч підприємців, або близько 12% від усіх підприємців, які наразі діють на ринку (незалежно від типу суб’єкту господарювання чи системи оподаткування). Без перехідного періоду та спрощення системи адміністрування ПДВ, таке податкове навантаження означатиме, що вони або переходитимуть у тінь, або будуть ліквідовувати бізнес.</p>
<p>Виходить, що одномоментна реалізація кожного з описаних сценаріїв викличе шок і переформатування ринку. Євроінтеграційний сценарій є менш жорстким, але і він вимагає перехідного періоду для адаптації підприємців до нових правил гри: перебудови ланцюгів постачання продуктів і послуг з фокусом на контрагентах-платниках ПДВ, підняття цін і середньострокової втрати звичної кількості клієнтів.</p>
</section>
<section id="висновки" class="level3">
<h3 class="anchored" data-anchor-id="висновки">Висновки</h3>
<p>Проблема ухилення від сплати податків через структурування бізнесу за допомогою ФОП чи оформлення найманих працівників як ФОП є актуальною для України, вона дійсно створює нерівні правила гри на ринку та призводить до недоотриманих податкових надходжень; але зниження ліміту до 1 млн грн не вирішить цих проблем — натомість звузить базу оподаткування та спричинить шок для мікробізнесу, посилюючи тенденції до міграції та тінізації діяльності активних громадян.</p>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Маємо доступні дані за секцією ‘I’ КВЕД (“Тимчасове розмiщування й органiзацiя харчування”). Виходимо з того, що доходи від дільності за КВЕД 56, який входить до секції I, розподілені схожим чином.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>